// <auto-generated />
using System;
using AppAPI.Model.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240524085136_Lan7")]
    partial class Lan7
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAPI.Model.Data.BinhLuan", b =>
                {
                    b.Property<Guid>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhachHangMaKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("BinhLuan", (string)null);
                });

            modelBuilder.Entity("AppAPI.Model.Data.HoaDon", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChiGiaoHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KhachHangMaKhachHang")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaKhachHang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGiaoHang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayLapHoaDon")
                        .HasColumnType("datetime2");

                    b.Property<byte>("TrangThai")
                        .HasColumnType("tinyint");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("KhachHangMaKhachHang");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("AppAPI.Model.Data.HoaDonChiTiet", b =>
                {
                    b.Property<Guid>("MaHoaDon")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSize")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("LoaiSanPhamMaLoaiSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MauSacMaMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSanPham", "MaSize");

                    b.HasIndex("LoaiSanPhamMaLoaiSanPham");

                    b.HasIndex("MaSanPham");

                    b.HasIndex("MaSize");

                    b.HasIndex("MauSacMaMau");

                    b.ToTable("HoaDonChiTiet", (string)null);
                });

            modelBuilder.Entity("AppAPI.Model.Data.KhachHang", b =>
                {
                    b.Property<Guid>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDangNhap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("AppAPI.Model.Data.LoaiSanPham", b =>
                {
                    b.Property<Guid>("MaLoaiSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenLoaiSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoaiSanPham");

                    b.ToTable("LoaiSanPham");
                });

            modelBuilder.Entity("AppAPI.Model.Data.MauSac", b =>
                {
                    b.Property<Guid>("MaMau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenMau")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaMau");

                    b.ToTable("MauSac");
                });

            modelBuilder.Entity("AppAPI.Model.Data.SanPham", b =>
                {
                    b.Property<Guid>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChuDe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GiaMua")
                        .HasColumnType("int");

                    b.Property<string>("GioiTinh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinhHanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LoaiSanPhamMaLoaiSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MaLoaiSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaMau")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MauSacMaMau")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NgayNhapHang")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenSanPham")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThongTin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSanPham");

                    b.HasIndex("LoaiSanPhamMaLoaiSanPham");

                    b.HasIndex("MauSacMaMau");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("AppAPI.Model.Data.Size", b =>
                {
                    b.Property<Guid>("MaSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sizes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaSize");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("AppAPI.Model.Data.Size_SanPham", b =>
                {
                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MaSize")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MaSanPham", "MaSize");

                    b.HasIndex("MaSize");

                    b.ToTable("Size_SanPham", (string)null);
                });

            modelBuilder.Entity("AppAPI.Model.Data.BinhLuan", b =>
                {
                    b.HasOne("AppAPI.Model.Data.KhachHang", "KhachHang")
                        .WithMany("BinhLuans")
                        .HasForeignKey("KhachHangMaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppAPI.Model.Data.HoaDon", b =>
                {
                    b.HasOne("AppAPI.Model.Data.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("KhachHangMaKhachHang");

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("AppAPI.Model.Data.HoaDonChiTiet", b =>
                {
                    b.HasOne("AppAPI.Model.Data.LoaiSanPham", null)
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("LoaiSanPhamMaLoaiSanPham");

                    b.HasOne("AppAPI.Model.Data.HoaDon", "HoaDon")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_HoaDonChiTiet");

                    b.HasOne("AppAPI.Model.Data.SanPham", "SanPham")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_HoaDonChiTiet");

                    b.HasOne("AppAPI.Model.Data.Size", "Size")
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MaSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Size_HoaDonChiTiet");

                    b.HasOne("AppAPI.Model.Data.MauSac", null)
                        .WithMany("HoaDonChiTiets")
                        .HasForeignKey("MauSacMaMau");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("AppAPI.Model.Data.SanPham", b =>
                {
                    b.HasOne("AppAPI.Model.Data.LoaiSanPham", "LoaiSanPham")
                        .WithMany()
                        .HasForeignKey("LoaiSanPhamMaLoaiSanPham");

                    b.HasOne("AppAPI.Model.Data.MauSac", "MauSac")
                        .WithMany()
                        .HasForeignKey("MauSacMaMau");

                    b.Navigation("LoaiSanPham");

                    b.Navigation("MauSac");
                });

            modelBuilder.Entity("AppAPI.Model.Data.Size_SanPham", b =>
                {
                    b.HasOne("AppAPI.Model.Data.SanPham", "SanPham")
                        .WithMany("size_SanPhams")
                        .HasForeignKey("MaSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_Size_SanPham");

                    b.HasOne("AppAPI.Model.Data.Size", "Size")
                        .WithMany("size_SanPhams")
                        .HasForeignKey("MaSize")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Size_Size_SanPham");

                    b.Navigation("SanPham");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("AppAPI.Model.Data.HoaDon", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AppAPI.Model.Data.KhachHang", b =>
                {
                    b.Navigation("BinhLuans");

                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("AppAPI.Model.Data.LoaiSanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AppAPI.Model.Data.MauSac", b =>
                {
                    b.Navigation("HoaDonChiTiets");
                });

            modelBuilder.Entity("AppAPI.Model.Data.SanPham", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("size_SanPhams");
                });

            modelBuilder.Entity("AppAPI.Model.Data.Size", b =>
                {
                    b.Navigation("HoaDonChiTiets");

                    b.Navigation("size_SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
